// laokou-ui/src/views/monitor/server/index.vue
<template>
  <page-header-wrapper>
    <a-space direction="vertical" style="width: 100%">
      <a-row :gutter="24">
        <a-col :span="12">
          <a-card :loading="loading" title="CPU" :bordered="false">
            <a-row :gutter="24" v-if="server.cpu">
              <a-col :span="12">
                <a-space direction="vertical" size="large">
                  <a-statistic
                    title="核心数"
                    :value="server.cpu.cpuNum"
                    :value-style="{ color: '#3f8600' }"
                    style="margin-right: 50px"
                  >
                    <template #prefix>
                      <a-icon type="setting" />
                    </template>
                  </a-statistic>
                  <a-statistic
                    title="用户使用率"
                    :value="server.cpu.used"
                    :precision="2"
                    suffix="%"
                    :value-style="{ color: '#3f8600' }"
                    style="margin-right: 50px"
                  >
                    <template #prefix>
                      <a-icon type="team" />
                    </template>
                  </a-statistic>
                </a-space>
              </a-col>
              <a-col :span="12">
                <a-space direction="vertical" size="large">
                  <a-statistic
                    title="系统使用率"
                    :value="server.cpu.sys"
                    :precision="2"
                    suffix="%"
                    :value-style="{ color: '#3f8600' }"
                    style="margin-right: 50px"
                  >
                    <template #prefix>
                      <a-icon type="cloud-server" />
                    </template>
                  </a-statistic>
                  <a-statistic
                    title="当前空闲率"
                    :value="server.cpu.free"
                    :precision="2"
                    suffix="%"
                    :value-style="{ color: '#3f8600' }"
                    style="margin-right: 50px"
                  >
                    <template #prefix>
                      <a-icon type="inbox" />
                    </template>
                  </a-statistic>
                </a-space>
              </a-col>
            </a-row>
          </a-card>
        </a-col>
        <a-col :span="12">
          <a-card :loading="loading" title="内存" :bordered="false">
            <a-table
              :loading="loading"
              size="small"
              rowKey="name"
              :columns="memColumns"
              :data-source="memData"
              :pagination="false">
              <span slot="mem" slot-scope="text, record">
                <div :style="{color: record.name == '使用率' && text > 80 ? 'red' : ''}">
                  <a-icon type="warning" style="color:#FFCC00" v-if="record.name == '使用率' && text > 80" />
                  {{ text }} &nbsp;
                  <code v-if="record.name == '使用率'">%</code>
                  <code v-if="record.name != '使用率'">G</code>
                </div>
              </span>
              <span slot="jvm" slot-scope="text, record">
                <div :style="{color: record.name == '使用率' && text > 80 ? 'red' : ''}">
                  <a-icon type="warning" style="color:#FFCC00" v-if="record.name == '使用率' && text > 80" />
                  {{ text }} &nbsp;
                  <code v-if="record.name == '使用率'">%</code>
                  <code v-if="record.name != '使用率'">M</code>
                </div>
              </span>
            </a-table>
          </a-card>
        </a-col>
      </a-row>
      <a-row :gutter="24">
        <a-col :span="24">
          <a-card :loading="loading" title="服务器信息" :bordered="false">
            <a-descriptions :column="2" v-if="server.sys">
              <a-descriptions-item label="服务器名称">
                {{ server.sys.computerName }}
              </a-descriptions-item>
              <a-descriptions-item label="操作系统">
                {{ server.sys.osName }}
              </a-descriptions-item>
              <a-descriptions-item label="服务器IP">
                {{ server.sys.computerIp }}
              </a-descriptions-item>
              <a-descriptions-item label="系统架构">
                {{ server.sys.osArch }}
              </a-descriptions-item>
            </a-descriptions>
          </a-card>
        </a-col>
      </a-row>
      <a-row :gutter="24">
        <a-col :span="24">
          <a-card :loading="loading" title="Java虚拟机信息" :bordered="false">
            <a-descriptions :column="2" v-if="server.jvm">
              <a-descriptions-item label="Java名称">
                {{ server.jvm.name }}
              </a-descriptions-item>
              <a-descriptions-item label="Java版本">
                {{ server.jvm.version }}
              </a-descriptions-item>
              <a-descriptions-item label="启动时间">
                {{ server.jvm.startTime }}
              </a-descriptions-item>
              <a-descriptions-item label="运行时长">
                {{ server.jvm.runTime }}
              </a-descriptions-item>
              <a-descriptions-item label="安装路径">
                {{ server.jvm.home }}
              </a-descriptions-item>
              <a-descriptions-item label="项目路径">
                {{ server.sys.userDir }}
              </a-descriptions-item>
              <a-descriptions-item label="运行参数">
                {{ server.jvm.inputArgs }}
              </a-descriptions-item>
            </a-descriptions>
          </a-card>
        </a-col>
      </a-row>
      <a-row :gutter="24">
        <a-col :span="24">
          <a-card :loading="loading" title="磁盘状态" :bordered="false">
            <a-table
              :loading="loading"
              :size="tableSize"
              rowKey="dirName"
              :columns="sysColumns"
              :data-source="sysData"
              :pagination="false"
              :bordered="tableBordered"
            >
              <span slot="total" slot-scope="text">
                {{ text }}
              </span>
              <span slot="free" slot-scope="text">
                {{ text }}
              </span>
              <span slot="used" slot-scope="text">
                {{ text }}
              </span>
              <span slot="usage" slot-scope="text">
                <div :style="{color: text > 80 ? 'red' : ''}">
                  <a-icon type="warning" style="color:#FFCC00" v-if="text > 80" />
                  {{ text }}<code>%</code>
                </div>
              </span>
            </a-table>
          </a-card>
        </a-col>
      </a-row>
    </a-space>
  </page-header-wrapper>
</template>

<script>

import { getServer } from '@/api/monitor/server'
import { tableMixin } from '@/store/table-mixin'

export default {
  name: 'Server',
  mixins: [tableMixin],
  data () {
    return {
      server: [],
      loading: true,
      memColumns: [
        {
          title: '属性',
          dataIndex: 'name'
        },
        {
          title: '内存',
          dataIndex: 'mem',
          scopedSlots: { customRender: 'mem' }
        },
        {
          title: 'JVM',
          dataIndex: 'jvm',
          scopedSlots: { customRender: 'jvm' }
        }
      ],
      memData: [],
      sysColumns: [
        {
          title: '盘符路径',
          dataIndex: 'dirName',
          ellipsis: true
        },
        {
          title: '文件系统',
          dataIndex: 'sysTypeName'
        },
        {
          title: '盘符类型',
          dataIndex: 'typeName',
          ellipsis: true
        },
        {
          title: '总大小',
          dataIndex: 'total',
          scopedSlots: { customRender: 'total' }
        },
        {
          title: '可用大小',
          dataIndex: 'free',
          scopedSlots: { customRender: 'free' }
        },
        {
          title: '已用大小',
          dataIndex: 'used',
          scopedSlots: { customRender: 'used' }
        },
        {
          title: '已用百分比',
          dataIndex: 'usage',
          scopedSlots: { customRender: 'usage' }
        }
      ],
      sysData: []
    }
  },
  filters: {
  },
  created () {
    this.getList()
  },
  computed: {
  },
  watch: {
  },
  methods: {
    /** 查询服务信息 */
    getList () {
      // this.loading = true
      getServer().then(response => {
          const serverData = response.data
          this.server = serverData
          this.memData = [
            {
              name: '总内存',
              mem: serverData.mem.total,
              jvm: serverData.jvm.total
            },
            {
              name: '已用内存',
              mem: serverData.mem.used,
              jvm: serverData.jvm.used
            },
            {
              name: '剩余内存',
              mem: serverData.mem.free,
              jvm: serverData.jvm.free
            },
            {
              name: '使用率',
              mem: serverData.mem.usage,
              jvm: serverData.jvm.usage
            }
          ]
          this.sysData = serverData.sysFiles
          setTimeout(() => {
            this.loading = false
          }, 500)
        }
      )
    }
  }
}
</script>

// laokou-ui/app/(business)/monitor/server/page.tsx
"use client";

import { fetchApi } from "@/app/_modules/func";
import { PageContainer, ProCard } from "@ant-design/pro-components";
import { Statistic, Divider, Table } from "antd";
import type { TableProps } from "antd";
import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";

import {
  faMicrochip,
  faMemory,
  faServer,
  faMugHot,
  faHardDrive,
} from "@fortawesome/free-solid-svg-icons";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { Col, Row } from "@/node_modules/antd/es/index";

import CountUp from "react-countup";

//查询API
const queryAPI = "/api/monitor/server";

export default function Server() {
  const { push } = useRouter();
  const [data, setData] = useState(undefined as any);

  const columns: TableProps["columns"] = [
    {
      title: "盘符路径",
      dataIndex: "dirName",
      key: "dirName",
    },
    {
      title: "文件系统",
      dataIndex: "sysTypeName",
      key: "sysTypeName",
    },
    {
      title: "盘符类型",
      dataIndex: "typeName",
      key: "typeName",
    },
    {
      title: "总大小",
      dataIndex: "total",
      key: "total",
    },
    {
      title: "可用大小",
      dataIndex: "free",
      key: "free",
    },
    {
      title: "已用大小",
      dataIndex: "used",
      key: "used",
    },
    {
      title: "已用百分比",
      dataIndex: "usage",
      key: "usage",
      render: (text) => <>{text}%</>,
    },
  ];

  //查询数据
  const queryData = async () => {
    const body = await fetchApi(queryAPI, push);
    if (body !== undefined) {
      if (body.code == 200) {
        console.log("data:", body.data);
        setData(body.data);
      }
    }
  };

  useEffect(() => {
    queryData();
  }, []);

  const formatterDecimal = (value: any) => (
    <CountUp end={parseFloat(value)} separator="," decimals={2} />
  );

  return (
    <PageContainer title={false}>
      {data !== undefined && (
        <ProCard gutter={[16, 16]} style={{ marginBlockStart: 16 }} wrap>
          <ProCard
            title={
              <>
                <FontAwesomeIcon icon={faMicrochip} />
                <span style={{ marginLeft: 6 }}>CPU</span>
              </>
            }
            direction="row"
            headerBordered
            bordered
            hoverable
          >
            <ProCard>
              <Statistic title="核心数" value={data.cpu.cpuNum} />
            </ProCard>
            <Divider type="vertical" />
            <ProCard>
              <Statistic
                title="用户使用率"
                value={data.cpu.used}
                suffix="%"
                formatter={formatterDecimal}
              />
            </ProCard>
            <Divider type="vertical" />
            <ProCard>
              <Statistic
                title="系统使用率"
                value={data.cpu.sys}
                suffix="%"
                formatter={formatterDecimal}
              />
            </ProCard>
            <Divider type="vertical" />
            <ProCard>
              <Statistic
                title="当前空闲率"
                value={data.cpu.free}
                suffix="%"
                formatter={formatterDecimal}
              />
            </ProCard>
          </ProCard>

          <ProCard
            title={
              <>
                <FontAwesomeIcon icon={faMemory} />
                <span style={{ marginLeft: 6 }}>内存</span>
              </>
            }
            direction="row"
            headerBordered
            bordered
            hoverable
          >
            <ProCard title="总内存">
              <Statistic title="内存" value={data.mem.total} suffix="G" />
              <Statistic title="JVM" value={data.jvm.total} suffix="M" />
            </ProCard>
            <ProCard title="已用内存">
              <Statistic
                title="内存"
                value={data.mem.used}
                suffix="G"
                formatter={formatterDecimal}
              />
              <Statistic
                title="JVM"
                value={data.jvm.used}
                suffix="M"
                formatter={formatterDecimal}
              />
            </ProCard>
            <ProCard title="剩余内存">
              <Statistic
                title="内存"
                value={data.mem.free}
                suffix="G"
                formatter={formatterDecimal}
              />
              <Statistic
                title="JVM"
                value={data.jvm.free}
                suffix="M"
                formatter={formatterDecimal}
              />
            </ProCard>
            <ProCard title="使用率">
              <Statistic
                title="内存"
                value={data.mem.usage}
                suffix="%"
                valueStyle={{
                  color: data.mem.usage > 80 ? "#cf1322" : "inherit",
                }}
                formatter={formatterDecimal}
              />
              <Statistic
                title="JVM"
                value={data.jvm.usage}
                suffix="%"
                valueStyle={{
                  color: data.jvm.usage > 80 ? "#cf1322" : "inherit",
                }}
                formatter={formatterDecimal}
              />
            </ProCard>
          </ProCard>

          <ProCard
            title={
              <>
                <FontAwesomeIcon icon={faServer} />
                <span style={{ marginLeft: 6 }}>服务器信息</span>
              </>
            }
            direction="row"
            headerBordered
            bordered
            hoverable
          >
            <ProCard>
              <Statistic title="服务器名称" value={data.sys.computerName} />
            </ProCard>
            <ProCard>
              <Statistic title="服务器IP" value={data.sys.computerIp} />
            </ProCard>
            <ProCard>
              <Statistic title="操作系统" value={data.sys.osName} />
            </ProCard>
            <ProCard>
              <Statistic title="系统架构" value={data.sys.osArch} />
            </ProCard>
          </ProCard>

          <ProCard
            title={
              <>
                <FontAwesomeIcon icon={faMugHot} />
                <span style={{ marginLeft: 6 }}>Java虚拟机信息</span>
              </>
            }
            direction="column"
            headerBordered
            bordered
            hoverable
          >
            <Row gutter={[0, 16]}>
              <Col span={12}>
                <Statistic title="名称" value={data.jvm.name} />
              </Col>
              <Col span={12}>
                <Statistic title="版本" value={data.jvm.version} />
              </Col>
            </Row>
            <Row gutter={[0, 16]}>
              <Col span={12}>
                <Statistic title="启动时间" value={data.jvm.startTime} />
              </Col>
              <Col span={12}>
                <Statistic title="运行时长" value={data.jvm.runTime} />
              </Col>
            </Row>
            <Row gutter={[0, 16]}>
              <Col span={24}>
                <Statistic title="安装路径" value={data.jvm.home} />
              </Col>
            </Row>
            <Row gutter={[0, 16]}>
              <Col span={24}>
                <Statistic title="项目路径" value={data.sys.userDir} />
              </Col>
            </Row>
            <Row gutter={[0, 16]}>
              <Col span={24}>
                <Statistic title="运行参数" value={data.jvm.inputArgs} />
              </Col>
            </Row>
          </ProCard>

          <ProCard
            title={
              <>
                <FontAwesomeIcon icon={faHardDrive} />
                <span style={{ marginLeft: 6 }}>磁盘状态</span>
              </>
            }
            headerBordered
            bordered
            hoverable
          >
            <Table columns={columns} dataSource={data.sysFiles} />
          </ProCard>
        </ProCard>
      )}
    </PageContainer>
  );
}
